apiVersion: infrastructure.capi.demo/v1alpha1
kind: MachinePool
metadata:
  labels:
    app.kubernetes.io/name: capi-demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: machinepool-sample
spec:
  # TODO(user): Add fields here
